require("core.pack")
require("core.statusline")
require("core.diagnostics")

require("vim._core.ui2").enable({})

require("config.options")
require("config.keymaps")
require("config.autocmds")

require("plugins.lsp")
-- require("plugins.yazi")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.colorscheme")
require("plugins.conform")
require("plugins.gitsigns")
require("plugins.which-key")
require("plugins.lazygit")
require("plugins.lint")
require("plugins.blink")
require("plugins.indent-blankline")
require("plugins.comments")
